### ISSUE TITLE
Ps3 Support

### ISSUE THREAD

**Issue by hkbrowny** [Fireboyd78/driver-tools#1]
Hey mate, 

The --big argument doesn't work when compiling. 

I've been using the software on the ps3 version of the game and when you use --big and --compile it doesnt seem to take the endianness in to account. 

any chance you could take a look?

[scriptsluascripts.fchunk.zip](https://github.com/Fireboyd78/driver-tools/files/4331968/scriptsluascripts.fchunk.zip)
[CHNK.zip](https://github.com/Fireboyd78/driver-tools/files/4331969/CHNK.zip)
[scriptsluascripts.fchunk.dat.zip](https://github.com/Fireboyd78/driver-tools/files/4331970/scriptsluascripts.fchunk.dat.zip)

**Comment by hkbrowny** [comment]
Just an update, i tried using the patching function instead. Gives me ERROR: Big-Endian scripts cannot be compiled at this time!

Is this something that could be added in?

**Comment by Fireboyd78** [comment]
Hi there! Sorry for the long delay in getting back to you.

Unfortunately, support for big-endian scripts would require a modified version of the Lua 5.1.4 compiler. My decompiler supports these just fine, but the actual Lua compiler itself is setup for little-endian (which is what the PC version uses).

I currently have no plans on supporting these types of scripts, due to the large amounts of effort required in making such a thing possible. If this is something a lot of people wish to see, I may consider it in the future.
